import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import PageHeader from "../components/PageHeader";
import StatCard from "../components/StatCard";
import StatusBadge from "../components/StatusBadge";
import Icon from "../components/Icon";
import { operationsApi, workersApi, equipmentApi, safetyApi, documentsApi } from "../services/api";
export default function Dashboard(){
 const {user}=useAuth(),navigate=useNavigate(),officer=user.role==="Officer"; const [ops,setOps]=useState([]),[safety,setSafety]=useState([]),[equipment,setEquipment]=useState([]),[counts,setCounts]=useState({workers:0,documents:0}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let alive=true;(async()=>{try{const [o,s,e,w,d]=await Promise.all([operationsApi.list(),safetyApi.list(),equipmentApi.list(),workersApi.list(),documentsApi.list()]);if(!alive)return;setOps(o.data);setSafety(s.data);setEquipment(e.data);setCounts({workers:w.data.length,documents:d.data.length});}catch(err){if(alive)setError(err?.response?.data?.message||"Could not load dashboard data.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 return <div><PageHeader eyebrow="OVERVIEW" title={`Good morning, ${(user?.name || "User").split(" ")[0]||user.name}`} description={officer?"Here is the current overview of your records workspace.":"Here is the information available to your worker account."} action={officer&&<button className="btn primary" onClick={()=>navigate("/operations")}><Icon name="plus" size={18}/> Add Operation</button>}/>{error&&<div className="notice"><Icon name="shield"/><span>{error}</span></div>}<div className="stats-grid"><StatCard title={officer?"Completed Operations":"My Operations"} value={ops.length} note="Live database" icon="layers" accent="blue"/><StatCard title={officer?"Total Workers":"Safety Records"} value={officer?counts.workers:safety.length} note="Live database" icon={officer?"users":"shield"} accent="green"/><StatCard title={officer?"Equipment":"Assigned Equipment"} value={equipment.length} note="Live database" icon="box" accent="purple"/><StatCard title={officer?"Safety Checks":"Documents"} value={officer?safety.length:counts.documents} note="Live database" icon={officer?"shield":"file"} accent="orange"/></div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>{officer?"Recent completed operations":"My recent operations"}</h2><p>Live records from the database.</p></div><button className="text-btn" onClick={()=>navigate(officer?"/operations":"/my-operations")}>View all <Icon name="arrow" size={16}/></button></div><div className="mini-list">{loading?<div className="table-empty">Loading...</div>:ops.slice(0,4).map(op=><div className="list-row" key={op.id}><div className="list-main"><div className="list-icon blue"><Icon name="layers" size={17}/></div><div><strong>{op.id}</strong><span>{op.location} • {op.date}</span></div></div><StatusBadge>{op.status}</StatusBadge></div>)}</div></section>
 <section className="panel"><div className="panel-head"><div><h2>Safety checks</h2><p>Latest administrative records.</p></div><button className="text-btn" onClick={()=>navigate(officer?"/safety-checks":"/my-safety")}>View all <Icon name="arrow" size={16}/></button></div><div className="mini-list">{loading?<div className="table-empty">Loading...</div>:safety.slice(0,4).map(item=><div className="list-row" key={item.id}><div className="list-main"><div className="list-icon green"><Icon name="shield" size={17}/></div><div><strong>{item.id}</strong><span>{item.operation} • {item.date}</span></div></div><StatusBadge>{item.status}</StatusBadge></div>)}</div></section></div>
 <section className="panel"><div className="panel-head"><div><h2>Equipment status</h2><p>Live equipment records.</p></div><button className="text-btn" onClick={()=>navigate("/equipment")}>Open equipment <Icon name="arrow" size={16}/></button></div><div className="equipment-strip">{equipment.slice(0,4).map(e=><div className="equipment-card" key={e.id}><div className="equipment-top"><div className="equipment-symbol"><Icon name="box"/></div><StatusBadge>{e.status}</StatusBadge></div><strong>{e.name}</strong><span>{e.id} • {e.category}</span><div className="equipment-meta"><span>Assigned</span><b>{e.assigned}</b></div></div>)}</div></section>
 </div>;
}
