import { useEffect, useMemo, useState } from "react";
import PageHeader from "../components/PageHeader";
import TableToolbar from "../components/TableToolbar";
import StatusBadge from "../components/StatusBadge";
import Modal from "../components/Modal";
import Icon from "../components/Icon";
import { equipmentApi } from "../services/api";
import { useAuth } from "../context/AuthContext";
const blank={id:"",name:"",category:"",condition:"",assigned:"",inspection:"",maintenance:"",status:"Available"};
export default function Equipment(){
 const {user}=useAuth(); const officer=user?.role==="Officer";
 const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const {data}=await equipmentApi.list({search});setRows(data);setError("")}catch(e){setError(e?.response?.data?.message||"Could not load equipment.")}finally{setLoading(false)}}; useEffect(()=>{load()},[search]);
 const filtered=useMemo(()=>rows,[rows]);
 const save=async e=>{e.preventDefault();try{if(rows.some(x=>x.id===form.id))await equipmentApi.update(form.id,form);else await equipmentApi.create(form);setOpen(false);setForm(blank);await load()}catch(e){setError(e?.response?.data?.message||"Could not save equipment.")}};
 const remove=async id=>{if(!confirm(`Delete ${id}?`))return;try{await equipmentApi.remove(id);await load()}catch(e){setError(e?.response?.data?.message||"Could not delete equipment.")}};
 return <div><PageHeader eyebrow="ASSETS" title="Equipment" description="Track administrative equipment records, condition and assigned person." action={officer&&<button className="btn primary" onClick={()=>{setForm(blank);setOpen(true)}}><Icon name="plus"/> Add Equipment</button>}/>{error&&<div className="notice"><Icon name="shield"/><span>{error}</span></div>}<section className="panel table-panel"><TableToolbar search={search} setSearch={setSearch} placeholder="Search equipment..."/><div className="table-wrap"><table><thead><tr><th>Equipment</th><th>Category</th><th>Condition</th><th>Assigned Person</th><th>Last Inspection</th><th>Next Maintenance</th><th>Status</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="8">Loading...</td></tr>:filtered.map(x=><tr key={x.id}><td><strong className="primary-text">{x.name}</strong><span className="cell-sub">{x.id}</span></td><td>{x.category}</td><td>{x.condition}</td><td>{x.assigned}</td><td>{x.inspection}</td><td>{x.maintenance}</td><td><StatusBadge>{x.status}</StatusBadge></td><td>{officer&&<div className="row-actions"><button className="icon-table" onClick={()=>{setForm(x);setOpen(true)}}><Icon name="edit"/></button><button onClick={()=>remove(x.id)}><Icon name="trash"/></button></div>}</td></tr>)}</tbody></table></div><div className="table-foot"><span>{filtered.length} equipment records</span><span className="demo-label">Live API</span></div></section>{officer&&<Modal open={open} onClose={()=>setOpen(false)} title={form.id?"Edit Equipment":"Add Equipment"} wide><form className="form-grid" onSubmit={save}>{[["id","Equipment ID"],["name","Equipment Name"],["category","Category"],["condition","Condition"],["assigned","Assigned Person"],["inspection","Last Inspection"],["maintenance","Next Maintenance"]].map(([k,l])=><label key={k}>{l}<input value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})} required/></label>)}<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Available</option><option>Assigned</option><option>Maintenance</option><option>Inactive</option></select></label><div className="modal-actions full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary">Save Equipment</button></div></form></Modal>}</div>;
}
