import { useEffect, useState } from "react";
import PageHeader from "../components/PageHeader";
import TableToolbar from "../components/TableToolbar";
import StatusBadge from "../components/StatusBadge";
import Modal from "../components/Modal";
import Icon from "../components/Icon";
import { locationsApi } from "../services/api";
const blank={id:"",site:"",area:"",status:"Active",remarks:""};
export default function Locations(){
 const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const {data}=await locationsApi.list({search});setRows(data);setError("")}catch(e){setError(e?.response?.data?.message||"Could not load locations.")}finally{setLoading(false)}}; useEffect(()=>{load()},[search]);
 const filtered=rows.filter(x=>`${x.id} ${x.site} ${x.area}`.toLowerCase().includes(search.toLowerCase()));
 const save=async e=>{e.preventDefault();try{if(rows.some(x=>x.id===form.id))await locationsApi.update(form.id,form);else await locationsApi.create(form);setOpen(false);setForm(blank);await load()}catch(e){setError(e?.response?.data?.message||"Could not save location.")}};
 return <div><PageHeader eyebrow="SITES" title="Locations" description="Manage site and area records used by completed operation records." action={<button className="btn primary" onClick={()=>{setForm(blank);setOpen(true)}}><Icon name="plus"/> Add Location</button>}/>{error&&<div className="notice"><Icon name="shield"/><span>{error}</span></div>}<section className="panel table-panel"><TableToolbar search={search} setSearch={setSearch} placeholder="Search locations..."/><div className="table-wrap"><table><thead><tr><th>Location ID</th><th>Site Name</th><th>Area</th><th>Status</th><th>General Remarks</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="6">Loading...</td></tr>:filtered.map(x=><tr key={x.id}><td><strong className="primary-text">{x.id}</strong></td><td>{x.site}</td><td>{x.area}</td><td><StatusBadge>{x.status}</StatusBadge></td><td>{x.remarks}</td><td><button className="icon-table" onClick={()=>{setForm(x);setOpen(true)}}><Icon name="edit"/></button></td></tr>)}</tbody></table></div><div className="table-foot"><span>{filtered.length} location records</span><span className="demo-label">Live API</span></div></section><Modal open={open} onClose={()=>setOpen(false)} title={form.id?"Edit Location":"Add Location"}><form className="form-grid" onSubmit={save}>{[["id","Location ID"],["site","Site Name"],["area","Area"]].map(([k,l])=><label key={k}>{l}<input value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})} required/></label>)}<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Review</option><option>Inactive</option></select></label><label className="full">General Remarks<textarea rows="4" value={form.remarks||""} onChange={e=>setForm({...form,remarks:e.target.value})}/></label><div className="modal-actions full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary">Save Location</button></div></form></Modal></div>;
}
