import { useEffect, useState } from "react";
import PageHeader from "../components/PageHeader";
import StatCard from "../components/StatCard";
import StatusBadge from "../components/StatusBadge";
import Icon from "../components/Icon";
import { reportsApi, locationsApi } from "../services/api";
export default function Reports(){
 const [location,setLocation]=useState("All"),[status,setStatus]=useState("All"),[safety,setSafety]=useState("All"),[data,setData]=useState({summary:{},rows:[]}),[locations,setLocations]=useState([]),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [report,loc]=await Promise.all([reportsApi.summary({location,status,safety}),locationsApi.list()]);setData(report.data);setLocations(loc.data);setError("")}catch(e){setError(e?.response?.data?.message||"Could not load report data.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[location,status,safety]);
 const exportCsv=async()=>{try{const r=await reportsApi.exportCsv({location,status,safety});const blob=new Blob([r.data],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="blasttrack-report.csv";a.click();URL.revokeObjectURL(a.href)}catch(e){setError(e?.response?.data?.message||"Could not export report.")}};
 const s=data.summary||{};
 return <div><PageHeader eyebrow="ANALYTICS" title="Reports" description="Filter and export administrative summaries from the records workspace." action={<div className="header-actions"><button className="btn secondary" onClick={exportCsv}><Icon name="download"/> Export CSV</button><button className="btn primary" onClick={load}><Icon name="chart"/> Generate Report</button></div>}/>{error&&<div className="notice"><Icon name="shield"/><span>{error}</span></div>}<div className="stats-grid three"><StatCard title="Filtered Operations" value={s.totalOperations??0} note="Live database" icon="layers" accent="blue"/><StatCard title="Passed Safety Checks" value={s.passedSafety??0} note="Current filters" icon="shield" accent="green"/><StatCard title="Needs Review" value={s.needsReview??0} note="Current filters" icon="pin" accent="purple"/></div><section className="panel filters-panel"><div className="filter-title"><Icon name="filter"/><div><strong>Report filters</strong><span>Filter live database records.</span></div></div><div className="report-filters"><label>Location<select value={location} onChange={e=>setLocation(e.target.value)}><option>All</option>{locations.map(x=><option key={x.id}>{x.site}</option>)}</select></label><label>Operation status<select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Completed</option><option>In Progress</option></select></label><label>Safety status<select value={safety} onChange={e=>setSafety(e.target.value)}><option>All</option><option>Passed</option><option>Pending</option><option>Needs Review</option></select></label></div></section><section className="panel table-panel"><div className="panel-head"><div><h2>Report results</h2><p>Results are loaded from the SQLite database.</p></div></div><div className="table-wrap"><table><thead><tr><th>Operation</th><th>Date</th><th>Location</th><th>Officer</th><th>Workers</th><th>Safety</th><th>Status</th></tr></thead><tbody>{loading?<tr><td colSpan="7">Loading...</td></tr>:data.rows.map(x=><tr key={x.id}><td><strong className="primary-text">{x.id}</strong></td><td>{x.date}</td><td>{x.location}</td><td>{x.officer}</td><td>{x.workers}</td><td><StatusBadge>{x.safety}</StatusBadge></td><td><StatusBadge>{x.status}</StatusBadge></td></tr>)}</tbody></table></div></section></div>;
}
