import { useEffect, useState } from "react";
import PageHeader from "../components/PageHeader";
import TableToolbar from "../components/TableToolbar";
import StatusBadge from "../components/StatusBadge";
import Modal from "../components/Modal";
import Icon from "../components/Icon";
import { safetyApi } from "../services/api";
const blank={id:"",operation:"",date:"",inspector:"",status:"Passed",remarks:""};
export default function SafetyChecks(){
 const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const {data}=await safetyApi.list({search});setRows(data);setError("")}catch(e){setError(e?.response?.data?.message||"Could not load safety checks.")}finally{setLoading(false)}}; useEffect(()=>{load()},[search]);
 const save=async e=>{e.preventDefault();try{if(rows.some(x=>x.id===form.id))await safetyApi.update(form.id,form);else await safetyApi.create(form);setOpen(false);setForm(blank);await load()}catch(e){setError(e?.response?.data?.message||"Could not save safety check.")}};
 const filtered=rows.filter(x=>`${x.id} ${x.operation} ${x.inspector}`.toLowerCase().includes(search.toLowerCase()));
 return <div><PageHeader eyebrow="COMPLIANCE RECORDS" title="Safety Checks" description="Manage safety-check records associated with completed operations." action={<button className="btn primary" onClick={()=>{setForm(blank);setOpen(true)}}><Icon name="plus"/> Add Safety Check</button>}/>{error&&<div className="notice"><Icon name="shield"/><span>{error}</span></div>}<section className="panel table-panel"><TableToolbar search={search} setSearch={setSearch} placeholder="Search safety checks..."/><div className="table-wrap"><table><thead><tr><th>Check ID</th><th>Operation</th><th>Inspection Date</th><th>Inspector</th><th>Safety Status</th><th>Remarks</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="7">Loading...</td></tr>:filtered.map(x=><tr key={x.id}><td><strong className="primary-text">{x.id}</strong></td><td>{x.operation}</td><td>{x.date}</td><td>{x.inspector}</td><td><StatusBadge>{x.status}</StatusBadge></td><td>{x.remarks}</td><td><button className="icon-table" onClick={()=>{setForm(x);setOpen(true)}}><Icon name="edit"/></button></td></tr>)}</tbody></table></div><div className="table-foot"><span>{filtered.length} safety records</span><span className="demo-label">Live API</span></div></section><Modal open={open} onClose={()=>setOpen(false)} title={form.id?"Edit Safety Check":"Add Safety Check"}><form className="form-grid" onSubmit={save}>{[["id","Safety Check ID"],["operation","Operation ID"],["date","Inspection Date"],["inspector","Inspector"]].map(([k,l])=><label key={k}>{l}<input value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})} required/></label>)}<label>Safety Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Passed</option><option>Pending</option><option>Needs Review</option></select></label><label className="full">Remarks<textarea rows="4" value={form.remarks||""} onChange={e=>setForm({...form,remarks:e.target.value})}/></label><div className="modal-actions full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary">Save Safety Check</button></div></form></Modal></div>;
}
