import { useEffect, useMemo, useState } from "react";
import PageHeader from "../components/PageHeader";
import TableToolbar from "../components/TableToolbar";
import StatusBadge from "../components/StatusBadge";
import Modal from "../components/Modal";
import Icon from "../components/Icon";
import { workersApi } from "../services/api";
const blank={id:"",name:"",employee:"",designation:"",contact:"",joining:"",status:"Active"};
export default function Workers(){
 const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[open,setOpen]=useState(false),[form,setForm]=useState(blank),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const {data}=await workersApi.list({search});setRows(data);setError("");}catch(e){setError(e?.response?.data?.message||"Could not load workers.");}finally{setLoading(false);}}; useEffect(()=>{load()},[search]);
 const filtered=useMemo(()=>rows,[rows]);
 const save=async e=>{e.preventDefault();try{if(rows.some(x=>x.id===form.id))await workersApi.update(form.id,form);else await workersApi.create(form);setOpen(false);setForm(blank);await load();}catch(e){setError(e?.response?.data?.message||"Could not save worker.");}};
 const remove=async id=>{if(!confirm(`Delete ${id}?`))return;try{await workersApi.remove(id);await load()}catch(e){setError(e?.response?.data?.message||"Could not delete worker.")}};
 return <div><PageHeader eyebrow="PEOPLE" title="Worker Management" description="Maintain worker profiles and account records." action={<button className="btn primary" onClick={()=>{setForm(blank);setOpen(true)}}><Icon name="plus"/> Add Worker</button>}/>{error&&<div className="notice"><Icon name="shield"/><span>{error}</span></div>}<section className="panel table-panel"><TableToolbar search={search} setSearch={setSearch} placeholder="Search workers..."/><div className="table-wrap"><table><thead><tr><th>Worker</th><th>Employee ID</th><th>Designation</th><th>Contact</th><th>Joining Date</th><th>Status</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="7">Loading...</td></tr>:filtered.map(x=><tr key={x.id}><td><div className="person-cell"><div className="avatar small">{x.name?.[0]||"?"}</div><div><strong>{x.name}</strong><span>{x.id}</span></div></div></td><td>{x.employee}</td><td>{x.designation}</td><td>{x.contact}</td><td>{x.joining}</td><td><StatusBadge>{x.status}</StatusBadge></td><td><div className="row-actions"><button onClick={()=>{setForm(x);setOpen(true)}}><Icon name="edit"/></button><button onClick={()=>remove(x.id)}><Icon name="trash"/></button></div></td></tr>)}</tbody></table></div><div className="table-foot"><span>{filtered.length} worker records</span><span className="demo-label">Live API</span></div></section><Modal open={open} onClose={()=>setOpen(false)} title={form.id?"Edit Worker":"Add Worker"}><form className="form-grid" onSubmit={save}>{[["id","Worker ID"],["name","Name"],["employee","Employee ID"],["designation","Designation"],["contact","Contact"],["joining","Joining Date"]].map(([k,l])=><label key={k}>{l}<input value={form[k]||""} type={k==="joining"?"date":"text"} onChange={e=>setForm({...form,[k]:e.target.value})} required/></label>)}<label>Account Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></select></label><div className="modal-actions full"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary">Save Worker</button></div></form></Modal></div>;
}
